version: '3'

services:
  todoback:
    build: ./todo-app/back-end
    ports:
      - '3001:3001'

  todofront:
    build: ./todo-app/front-end
    enviroment:
     - REACT_APP_API_HOST=todoback
    depends_on:
      - 'todoback'
    ports:
      - '3000:3000'

  todotests:
    build: ./todo-app/todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - 'todofront'
      - 'todoback'
